// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "XXXXX"; 

const char SSID[]               = "XXXXX";    // Network SSID (name)
const char PASS[]               = "XXXXX";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "XXXXX";    // Secret device password

void onTempChange();
void onHumChange();

CloudTemperatureSensor temp;
CloudRelativeHumidity hum;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(hum, READWRITE, ON_CHANGE, onHumChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
