// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9a36d6fa-8db8-40d9-a1ef-e84384d08c96";

const char SSID[]               = "Arkaosi";    // Network SSID (name)
const char PASS[]               = "25011971";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "BzJr0J5R0O?6BMqEw8GHajprq";    // Secret device password

void onTempChange();
void onHumChange();

CloudTemperatureSensor temp;
CloudRelativeHumidity hum;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(hum, READWRITE, ON_CHANGE, onHumChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
